### ISSUE TITLE
Labeling Ordination Plots

### ISSUE THREAD

**Issue by deltoroi** [gavinsimpson/ggvegan#20]
Hello, I just used ggvegan to plot a NMDS. Two questions: 

Is there an argument that will allow the site and species names to be labeled?
 Is there a way to plot ellipses on this ordination plot?

**Comment by jammah** [comment]
No answer to this question?

**Comment by gavinsimpson** [comment]
Apologies @deltoroi & @jammah for not circling back to this... too many packages, too little time.

The `geom` argument takes `"points"` or `"text"`, but I suspect you want the points *and* the labels. In which case that is not offered in these `autoplot` methods, but it is relatively straightforward to do this yourself using geoms from the **ggrepel** package:

```r
library("vegan")
library("ggvegan")
library("dplyr")
library("ggrepel")

data(varespec)

# with the development version of vegan
set.seed(23)
sol <- metaMDS(varespec, dist = "hellinger", autotransform = FALSE)
# if using the CRAN version of vegan
# set.seed(2375)
# sol <- metaMDS(decostand(varespec, method = "hellinger"), dist = "euclidean")

scrs <- fortify(sol)

ggplot(data = scrs, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(colour = Score, shape = Score)) +
  geom_text_repel(mapping = aes(label = Label), max.overlaps = 20, seed = 34) +
  coord_equal()
```

![issue-20-answer-img](https://user-images.githubusercontent.com/514696/192738529-949f25e8-eb74-45fc-a89a-1e4680ebe6e9.png)


You could do this with plain old `geom_label` or `geom_text` by setting the `nudge_x` and `nudge_y` arguments but **ggrepel** takes care of overlapping labels which is likely to occur with these kinds of ordinations.

**Comment by jammah** [comment]
Many thanks @gavinsimpson
