### ISSUE TITLE
Issue downloading ggvegan in R (Version 1.1.463)

### ISSUE THREAD

**Issue by georginahunt** [gavinsimpson/ggvegan#22]
I am having issues istalling ggvegan in to R after running the code:
library(devtools)
devtools::install_github("gavinsimpson/ggvegan")

It comes up with the error:
Error: Failed to install 'ggvegan' from GitHub:
  (converted from warning) packages ‘vegan’, ‘ggplot2’, ‘tidyr’, ‘permute’, ‘tibble’, ‘dplyr’, ‘purrr’, ‘stringr’ are in use and will not be installed

Please can someone help assist with this issue as I am looking to use ggvegan to create an autoplot for a cca?

Thanks!

**Comment by jcvdav** [comment]
Hi @georginahunt - Not sure, but your problem might be caused by having those packages loaded in your environment. If running R on RStudio, try restarting R (Session >> Restart R) or (`Ctrl` + `Shift` + `F10`). Then run:
```
library(devtools)
devtools::install_github("gavinsimpson/ggvegan")
```

**Comment by georginahunt** [comment]
Thanks for your reply. I have removed everything from my environment and tried restarting but now the following error has come up:

```
devtools::install_github("gavinsimpson/ggvegan")
Downloading GitHub repo gavinsimpson/ggvegan@master
These packages have more recent versions available.
Which would you like to update?

 1: All                                     
 2: CRAN packages only                      
 3: None                                    
 4: purrr      (0.2.5    -> 0.3.2   ) [CRAN]
 5: Rcpp       (1.0.1    -> 1.0.2   ) [CRAN]
 6: stringi    (1.2.4    -> 1.4.3   ) [CRAN]
 7: stringr    (1.3.1    -> 1.4.0   ) [CRAN]
 8: R6         (2.3.0    -> 2.4.0   ) [CRAN]
 9: colorspace (1.3-2    -> 1.4-1   ) [CRAN]
10: pillar     (1.3.0    -> 1.4.2   ) [CRAN]
11: assertthat (0.2.0    -> 0.2.1   ) [CRAN]
12: backports  (1.1.2    -> 1.1.4   ) [CRAN]
13: BH         (1.66.0-1 -> 1.69.0-1) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

Installing 1 packages: glue
Installing package into ‘H:/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/glue_1.3.1.zip'
Content type 'application/zip' length 172510 bytes (168 KB)
downloaded 168 KB

package ‘glue’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\b1026869\AppData\Local\Temp\RtmpIVdWES\downloaded_packages
√  checking for file 'C:\Users\b1026869\AppData\Local\Temp\RtmpIVdWES\remotes3df013b62ec4\gavinsimpson-ggvegan-4b73ec1/DESCRIPTION' ...
-  preparing 'ggvegan':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ggvegan_0.1-0.tar.gz'
   
Installing package into ‘H:/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'ggvegan' ...
** R
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'vegan' was built under R version 3.5.3
ERROR: lazy loading failed for package 'ggvegan'
* removing 'H:/R/win-library/3.5/ggvegan'
In R CMD INSTALL
Error: Failed to install 'ggvegan' from GitHub:
  (converted from warning) installation of package ‘C:/Users/b1026869/AppData/Local/Temp/RtmpIVdWES/file3df033cd2e7c/ggvegan_0.1-0.tar.gz’ had non-zero exit status

```

**Comment by gavinsimpson** [comment]
@georginahunt From the transcript it looks like;

1. You have lots of packages that need updating,
2. You selected to *not* update these packages when installing **ggvegan**.

To confirm, start a clean R (as per @jcvdav’s previous reply) then do

    update.packages(ask = FALSE, checkBuilt = TRUE)

And make sure that you update your packages before trying to install **ggvegan** again.

**Comment by georginahunt** [comment]
Hello,

I am having more issues when trying to install ggvegan using:

install.packages("devtools")
devtools::install_github("gavinsimpson/ggvegan")

Even trying to update all of my packages in R (using the code you previously) suggested, it keeps coming up with the following error message:

```
library(devtools)
Loading required package: usethis
Warning messages:
1: package ‘devtools’ was built under R version 3.5.3 
2: package ‘usethis’ was built under R version 3.5.3 
> devtools::install_github("gavinsimpson/ggvegan")
Downloading GitHub repo gavinsimpson/ggvegan@master
√  checking for file 'C:\Users\b1026869\AppData\Local\Temp\RtmpM9UakU\remotes2bc456322ac1\gavinsimpson-ggvegan-4b73ec1/DESCRIPTION' ...
-  preparing 'ggvegan':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ggvegan_0.1-0.tar.gz'
   
Installing package into ‘H:/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'ggvegan' ...
** R
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'vegan' was built under R version 3.5.3
ERROR: lazy loading failed for package 'ggvegan'
* removing 'H:/R/win-library/3.5/ggvegan'
In R CMD INSTALL
Error: Failed to install 'ggvegan' from GitHub:
  (converted from warning) installation of package ‘C:/Users/b1026869/AppData/Local/Temp/RtmpM9UakU/file2bc42b025913/ggvegan_0.1-0.tar.gz’ had non-zero exit status
```

Do you have any advice on how to get around this?

Thanks,
Georgina

**Comment by gavinsimpson** [comment]
The error (see the first line starting `Error : (converted from warning)` is that the version of vegan (on your computer) was built with 3.5.3, which I presume is not the version of R you are now running? This is normally a warning, but *devtools* upgrades warnings to errors (it seems; or something did), and it is that warning-upgraded-or-error that is causing this to fail.

I presume that if you were to update vegan to be built with your current R, this problem will go away. To do a package update and also update all packages not built with the current R version, do:

    updated.packages(checkBuilt = TRUE, ask = FALSE)

If you just want to try to get *vegan* working, then just reinstall it:

    install.packages(“vegan”)

**Comment by georginahunt** [comment]
Thanks. I have just updated my R and I am using Version 3.6.0 and even after updating all packages, the same error is still coming up. I am trying to download ggvegan. Vegan is working fine but I am still having issues with using devtools::install_github("gavinsimpson/ggvegan"). I don't really know what else to try.

Thanks,
Georgina

**Comment by georginahunt** [comment]
Hi again,

I still don't understand why ggvegan can't be installed. Since updating to 3.60, do I need to install particular packages first before install ggvegan? I have installed some (i.e. vegan, ggplot2, rlang, devtools), however the following error(s) are showing up:

```
> update.packages(ask = FALSE, checkBuilt = TRUE)
Warning: package 'aplpack' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'backports' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'callr' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'car' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'carData' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'checkmate' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'clipr' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'coda' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'curl' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'data.table' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'digest' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'doParallel' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'dplyr' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'e1071' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'effects' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'ellipsis' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'evaluate' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'foreach' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'ggplot2' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'haven' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'Hmisc' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'hms' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'htmlTable' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'htmltools' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'htmlwidgets' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'httpuv' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'iterators' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'knitr' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'later' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'lavaan' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'maptools' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'markdown' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'mime' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'mvtnorm' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'numDeriv' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'openxlsx' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'pillar' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'pkgconfig' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'pls' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'processx' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'progress' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'promises' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'purrr' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'quadprog' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'quantreg' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'R.oo' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'R.utils' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'R6' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'Rcpp' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'RcppEigen' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'rgl' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'rjags' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'rmarkdown' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'scales' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'shiny' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'sp' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'spam' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'survival' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'tibble' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'tidyr' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'tinytex' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'vegan' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'xfun' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'zip' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'zoo' in library 'J:/R-Library/3.6.0' will not be updated
Warning: package 'boot' in library 'C:/Program Files/R/R-3.6.0/library' will not be updated
Warning: package 'cluster' in library 'C:/Program Files/R/R-3.6.0/library' will not be updated
Warning: package 'foreign' in library 'C:/Program Files/R/R-3.6.0/library' will not be updated
Warning: package 'KernSmooth' in library 'C:/Program Files/R/R-3.6.0/library' will not be updated
Warning: package 'mgcv' in library 'C:/Program Files/R/R-3.6.0/library' will not be updated
Warning: package 'nlme' in library 'C:/Program Files/R/R-3.6.0/library' will not be updated
Warning: package 'survival' in library 'C:/Program Files/R/R-3.6.0/library' will not be updated
Warning in install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  'lib = "J:/R-Library/3.6.0"' is not writable
Error in install.packages(update[instlib == l, "Package"], l, repos = repos,  : 
  unable to install packages
> devtools::install_github("gavinsimpson/ggvegan")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: namespace ‘rlang’ 0.3.4 is already loaded, but >= 0.4.1 is required
> install.packages("devtools")
Installing package into ‘H:/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/devtools_2.2.1.zip'
Content type 'application/zip' length 342877 bytes (334 KB)
downloaded 334 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\b1026869\AppData\Local\Temp\RtmpsjaImG\downloaded_packages
> devtools::install_github("gavinsimpson/ggvegan")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: namespace ‘rlang’ 0.3.4 is already loaded, but >= 0.4.1 is required

```

**Comment by gavinsimpson** [comment]
I can't debug your local installation issues for you; a *J* drive would certainly be non-standard (you either have a *lot* of internal drives or you are working on a system that has seen quite some configuration beyond the normal). It looks like you might have fixed this later (installing to the `H` drive), but you still need to install newer versions of the packages that are on the J drive that R said it wouldn't update. Otherwise it will just keep on loading those outdated packages.

But here are some pointers from the warnings and errors you showed:

> Warning in install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  'lib = "J:/R-Library/3.6.0"' is not writable

You appear to be trying to install packages in a location that you do not have write permissions for on the J drive. I would suggest that you set up a folder as your R Package Library in your own directories where you do have write permissions so that you can install packages.

> devtools::install_github("gavinsimpson/ggvegan")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: namespace ‘rlang’ 0.3.4 is already loaded, but >= 0.4.1 is required

I think this means that you have *rlang* installed and loaded (i.e. in use)in the current session but that it is too old to meet the dependencies of the *pkgload* package that *devtools* is trying to use.

The last Error is related. Once you have installed these packages, it might be best to restart R so you have a clean session before you start to use. That may not fix the problem but it will get you closer.

This really is a local installation problem and not something I'm going to be able to help you with further; all of this seems to be related to having up-to-date dependencies for *devtools* or an up-to-date version of *vegan*, and nothing to do with *ggvegan** itself.

**Comment by ziels** [comment]
Just encountered this error. Fixed it with: 
`Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")`

**Comment by princechikezie** [comment]
`Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")`

Could you please explain how this fixed it? What does it mean for errors in R? Also had the same issues as above with a different but package and it worked

> Just encountered this error. Fixed it with:
> `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")`
> 
> Then, `devtools::install_github("gavinsimpson/ggvegan")` ran fine.

**Comment by JinjiPang** [comment]
hi, I encountered the same issue today.
I first run :  `1update.packages(ask= FALSE, checkBuilt = TRUE) to update all of my packages.`
Then I run :` library(devtools)`
                   `devtools::install_github("gavinsimpson/ggvegan")`

Then I for error message like this: 

> Installing package into ‘C:/Users/kimki/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'ggvegan' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for 'ggplot2' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace 'ellipsis' 0.3.1 is being loaded, but >= 0.3.2 is required
Error: package 'ggplot2' could not be loaded
Execution halted
ERROR: lazy loading failed for package 'ggvegan'
* removing 'C:/Users/kimki/Documents/R/win-library/4.0/ggvegan'
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\kimki\Documents\R\win-library\4.0\00LOCK\ellipsis\libs\x64\ellipsis.dll to C:\Users\kimki\Documents\R\win-library\4.0\ellipsis\libs\x64\ellipsis.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\kimki\Documents\R\win-library\4.0\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\kimki\Documents\R\win-library\4.0\rlang\libs\x64\rlang.dll: Permission denied
3: In i.p(...) :
  installation of package ‘C:/Users/kimki/AppData/Local/Temp/RtmpOQen4M/filecbfcba66fd/ggvegan_0.1-0.tar.gz’ had non-zero exit status

Could anyone have a look and let me know how to solve this issue?

**Comment by gavinsimpson** [comment]
Nothing; it should only affect something looking at that environmental variable and I think this is one set for the {remotes} 📦.

If you're concerned about this, start a new R session to do the installs and then close the session, that way the env variable will be deleted - it isn't preserved across sessions.
