### ISSUE TITLE
autoplot.rda issues

### ISSUE THREAD

**Issue by adrianacravo** [gavinsimpson/ggvegan#28]
Hello everyone,
I successfully installed the packages ggvegan, ggplot2 and ggfortify, however when I try to run the commands to plot my rda result (https://github.com/gavinsimpson/ggvegan/blob/master/R/autoplot.rda.R), I get across different error messages at different steps. The first problem is: when I run 
```
autoplot.rda <- function(rda.abund_Ao.Ach, axes = c(1,2), geom = c("point", "text"),
                         layers = c("species", "sites", "biplot", "centroids"),
                         arrows = TRUE, legend.position = "right",
                         title = NULL, subtitle = NULL, caption = NULL,
                         ylab, xlab, const, ...) {
 
 valid <- ggvegan:::valid_layers(rda.abund_Ao.Ach)       
 ok_layers <- ggvegan:::check_user_layers(layers, valid, message = TRUE)
 layers <- layers[ok_layers]         
 draw_list <- ggvegan:::layer_draw_list(valid, layers) 
 draw_list <- ggvegan:::layer_draw_list(valid)  

 laxes <- length(axes)
  if (laxes != 2L) {
    if (laxes > 2L) {
      axes <- rep(axes, length.out = 2L)  # shrink to required length
    } else {
      stop("Need 2 ordination axes to plot; only 1 was given.",
           call. = FALSE)
    }
  }
```

it creates the function autoplot.rda, but doesn't create the elements from the function. I mean, if I then type "geom" or "legend.position", e.g., I get _Error: object 'geom' not found_, so I need to run them individually afterwards anyway, even if I already had the function.. Later on, when I get to  `if(missing(xlab)) {  xlab <- vars[1] }`, it also doesn't work (_Error in missing(xlab) : 'missing' can only be used for arguments_) and finally, if I skip this part and go directly to the plotting stage, `plt <- plt + theme(legend.position = legend.position)`, I get the final error message: _Error in as.character(x$label) : cannot coerce type 'closure' to vector of type 'character'_. Did someone already come across those error messages? 
I know it's too much to ask, but I'm also not sure how to track or identify where those problems come from, any help is appreciated. 
Thanks a lot!
Adriana

**Comment by gavinsimpson** [comment]
Why are you trying to create a new function `autoplot.rda`?

If you have a fitted RDA object, `rda.abund_Ao.Ach` then you should just be able to do `autoplot(rda.abund_Ao.Ach)` to generate the triplot.

Here's an example:

```r
library('vegan')
library('ggvegan')
data(varespec, varechem)

ord <- rda(varespec ~ ., data = varechem, scale = TRUE)

autoplot(ord, arrows = FALSE, scaling = "symmetric")
```
